# Generated by Django 5.2 on 2026-03-15 06:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimensionamento', '0002_alter_dimensionamento_fator_perda_decimal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_energia_kwh', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tarifa de Energia (R$/kWh)')),
                ('custo_disponibilidade_rs', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo de Disponibilidade (R$)')),
                ('investimento_total_rs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Investimento Total (R$)')),
                ('geracao_mensal_kwh', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Geração Mensal (kWh)')),
                ('economia_mensal_rs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Economia Mensal (R$)')),
                ('economia_anual_rs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Economia Anual (R$)')),
                ('payback_meses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payback (meses)')),
                ('payback_anos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payback (anos)')),
                ('economia_25_anos_rs', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Economia em 25 anos (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimensionamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculos_financeiros', to='dimensionamento.dimensionamento', verbose_name='Dimensionamento')),
            ],
            options={
                'verbose_name': 'Cálculo Financeiro',
                'verbose_name_plural': 'Cálculos Financeiros',
                'db_table': 'calculos_financeiros',
                'ordering': ['-created_at'],
            },
        ),
    ]
