# Generated by Django 6.0 on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models

import apps.documentos.defaults


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dimensionamento", "0004_dimensionamento_coordenadas_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviewTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data",
                    models.JSONField(
                        default=apps.documentos.defaults.get_default_preview_template_data,
                        verbose_name="Dados do template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template de Preview",
                "verbose_name_plural": "Templates de Preview",
                "db_table": "documentos_preview_templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PropostaPreviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Estado do preview")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimensionamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_state",
                        to="dimensionamento.dimensionamento",
                        verbose_name="Dimensionamento",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposal_states",
                        to="documentos.previewtemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado do Preview da Proposta",
                "verbose_name_plural": "Estados do Preview da Proposta",
                "db_table": "documentos_preview_states",
                "ordering": ["-updated_at"],
            },
        ),
    ]
