# Generated by Django 5.2 on 2026-03-13 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumos_mensais', models.JSONField(verbose_name='Consumos Mensais (12 meses)')),
                ('irradiacao_media_cidade', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Irradiação Média da Cidade')),
                ('fator_perda_decimal', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.9999)], verbose_name='Fator de Perda Decimal')),
                ('custo_kit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo do Kit')),
                ('custo_adicionais', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo de Adicionais')),
                ('margem_lucro_decimal', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem de Lucro Decimal')),
                ('imposto_servico_decimal', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Imposto de Serviço Decimal')),
                ('taxa_juros_mensal_decimal', models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Juros Mensal Decimal')),
                ('potencia_calculada_kwp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Potência Calculada (kWp)')),
                ('valor_total_sistema', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total do Sistema')),
                ('lucro_liquido_empresa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lucro Líquido da Empresa')),
                ('financiamento_parcelas', models.JSONField(verbose_name='Parcelas Financiamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimensionamentos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dimensionamento',
                'verbose_name_plural': 'Dimensionamentos',
                'db_table': 'dimensionamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
