# Generated by Django 5.2 on 2026-03-13 07:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionamento',
            name='fator_perda_decimal',
            field=models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.9999'))], verbose_name='Fator de Perda Decimal'),
        ),
        migrations.AlterField(
            model_name='dimensionamento',
            name='irradiacao_media_cidade',
            field=models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Irradiação Média da Cidade'),
        ),
    ]
