# Generated by Django 5.2 on 2026-03-09 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do vendedor', max_length=150, verbose_name='Nome')),
                ('cargo', models.CharField(help_text='Cargo/função do vendedor na empresa', max_length=100, verbose_name='Cargo')),
                ('telefone', models.CharField(help_text='Telefone com DDD (somente números)', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos numéricos (apenas números)', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail corporativo do vendedor', max_length=254, unique=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o vendedor está ativo no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='CPF do cliente (somente números)', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'CPF deve conter 11 dígitos'), django.core.validators.RegexValidator(message='CPF deve conter apenas números', regex='^\\d{11}$')], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, help_text='Telefone com DDD (opcional)', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 dígitos numéricos', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, help_text='E-mail do cliente (opcional)', max_length=254, verbose_name='E-mail')),
                ('cep', models.CharField(help_text='CEP da residência (somente números)', max_length=8, validators=[django.core.validators.MinLengthValidator(8, 'CEP deve conter 8 dígitos'), django.core.validators.RegexValidator(message='CEP deve conter apenas números', regex='^\\d{8}$')], verbose_name='CEP')),
                ('rua', models.CharField(help_text='Preenchido automaticamente via CEP', max_length=200, verbose_name='Rua/Logradouro')),
                ('bairro', models.CharField(help_text='Preenchido automaticamente via CEP', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Preenchido automaticamente via CEP', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Preenchido automaticamente via CEP', max_length=2, verbose_name='Estado (UF)')),
                ('numero', models.CharField(help_text='Número da residência', max_length=10, verbose_name='Número')),
                ('consumo_kwh_mes', models.PositiveIntegerField(help_text='Consumo médio mensal em kWh conforme conta de energia', verbose_name='Consumo (kWh/mês)')),
                ('tipo_ligacao', models.CharField(choices=[('monofasico', 'Monofásico'), ('bifasico', 'Bifásico'), ('trifasico', 'Trifásico')], help_text='Tipo de ligação elétrica da residência', max_length=20, verbose_name='Tipo de Ligação')),
                ('tipo_telhado', models.CharField(choices=[('ceramico', 'Cerâmico'), ('metalico', 'Metálico'), ('laje', 'Laje'), ('fibrocimento', 'Fibrocimento')], help_text='Material do telhado para instalação dos painéis', max_length=20, verbose_name='Tipo de Telhado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vendedor', models.ForeignKey(help_text='Vendedor responsável pelo atendimento', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
